# Generated by Django 4.2.3 on 2023-11-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='created',
        ),
    ]
